# Generated by Django 3.1 on 2020-08-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0002_auto_20200819_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='friend_took', to='books_shelf.Friend', verbose_name='Друг'),
        ),
    ]
