# Generated by Django 3.1 on 2020-08-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0003_auto_20200819_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='books_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество изданных книг'),
        ),
    ]
