# Generated by Django 3.1 on 2020-08-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0004_publisher_books_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество книг'),
        ),
    ]
