# Generated by Django 3.1 on 2020-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0005_author_books_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='book_title',
            field=models.ManyToManyField(blank=True, related_name='taken_book', to='books_shelf.Book', verbose_name='Книга'),
        ),
    ]
