# Generated by Django 3.1 on 2020-08-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0006_auto_20200821_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
    ]
