# Generated by Django 3.1 on 2020-08-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0007_remove_book_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='book_title',
            new_name='books',
        ),
    ]
