# Generated by Django 3.1 on 2020-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0008_auto_20200821_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='balance',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Остаток'),
        ),
        migrations.AddField(
            model_name='book',
            name='rented',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Переданы в аренду'),
        ),
        migrations.AlterField(
            model_name='book',
            name='copy_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество экземпляров'),
        ),
    ]
