# Generated by Django 3.1 on 2020-08-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0009_auto_20200822_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='author_books', to='books_shelf.Book', verbose_name='Книги автора'),
        ),
    ]
