# Generated by Django 3.1 on 2020-08-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0010_author_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
    ]
