# Generated by Django 3.1 on 2020-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0011_remove_author_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, null='True', related_name='taken_book', to='books_shelf.Book', verbose_name='Книга'),
        ),
    ]
