# Generated by Django 3.1 on 2020-08-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0012_auto_20200822_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='taken_book', to='books_shelf.Book', verbose_name='Книга'),
        ),
    ]
