# Generated by Django 3.1 on 2020-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0014_auto_20200823_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='rented_by_friend', to='books_shelf.Friend', verbose_name='Друг'),
        ),
    ]
