# Generated by Django 3.1 on 2020-08-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_shelf', '0016_auto_20200827_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='rented_by_friend', to='books_shelf.Friend', verbose_name='Друг'),
        ),
    ]
